---



# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Tlhey's Website
subtitle: ''
description: ''
keywords:
author: Tlhey
language: en
timezone: ''

avatar:
  img: img/Avatar.jpg
  effect: false


index_img: transparent
# The height of top_img, eg: 300px/300em/300rem (主頁top_img高度)
index_top_img_height: 1000px
# Website Background (設置網站背景)
# can set it to color or image (可設置圖片 或者 顔色)
# The formal of image: url(http://xxxxxx.com/xxx.jpg)
background: /img/Background2.png
# Footer Background
# Add mask to header or footer (为 header 或 footer 添加黑色半透遮罩)
mask: true
footer_img: true


# Navi
nav:
  # Navigation bar logo image
  logo: img/Navi.jpg
  display_title: true
  # Whether to fix navigation bar
  fixed: false


# Menu  
menu:
  Home: / || fas fa-home
  Archives: /archives/ || fas fa-archive
  Tags: /tags/ || fas fa-tags
  Categories: /categories/ || fas fa-folder-open
  List||fas fa-list:
    Music: /music/ || fas fa-music
    Movie: /movies/ || fas fa-video
  Link: /link/ || fas fa-link
  About: /about/ || fas fa-heart

# Emoji
# markdown:
#   render:
#     html: true
#     xhtmlOut: false
#     breaks: true
#     linkify: true
#     typographer: true
#     quotes: '“”‘’'
#   plugins:
#     - markdown-it-footnote
#     - markdown-it-sup
#     - markdown-it-sub
#     - markdown-it-abbr
#     - markdown-it-emoji
#   anchors:
#     level: 2
#     collisionSuffix: 'v'
#     permalink: false
#     permalinkClass: header-anchor
#     permalinkSymbol: ¶


# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://tlhey.github.io/
root: 
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

# Pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
include:
exclude:
ignore:

# Extensions
theme: butterfly

# Deployment
deploy:
  type: git
  repo: https://github.com/Tlhey/tlhey.github.io
  branch: master

markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
  plugins:
  anchors:
    level: 1
    collisionSuffix: ''





cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  default_cover:
  - /img/bc1.jpg
  - /img/bc2.jpg
  - /img/bc3.jpg
  - /img/bc4.jpg
  - /img/bc5.jpeg
  - /img/bc6.jpeg
  - /img/bc7.jpeg
  - /img/bc8.jpeg
  - /img/bc9.jpeg
  - /img/bc10.jpeg
  - /img/bc11.jpeg
  - /img/bc12.jpeg
  - /img/bc13.jpeg
  - /img/bc14.jpeg
  - /img/bc15.jpeg
  - /img/bc16.jpeg
  - /img/bc17.jpeg
  - /img/bc18.jpeg
  - /img/bc19.jpeg
  - /img/bc20.jpeg
  - /img/bc21.jpeg
  - /img/bc22.jpeg

    